'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default

    '''<summary>
    '''formDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formDefault As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Label_vitaz_predoslej_hry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_vitaz_predoslej_hry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_vitaz_predoslej_hry_meno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_vitaz_predoslej_hry_meno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_pocet_kol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_pocet_kol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadioButtonList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Label_1sprava control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_1sprava As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label_2sprava control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_2sprava As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Button_elzi_loads_competition_page control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_elzi_loads_competition_page As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button_tomas_loads_competition_page control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_tomas_loads_competition_page As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''div_elzi_body_z_minulej_hry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_elzi_body_z_minulej_hry As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label_elzi_cislo_pocet_vitazstiev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_elzi_cislo_pocet_vitazstiev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_tomas_body_z_minulej_hry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_tomas_body_z_minulej_hry As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label_tomas_cislo_pocet_vitazstiev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_tomas_cislo_pocet_vitazstiev As Global.System.Web.UI.WebControls.Label
End Class
